---
# optional, will be applied to all hashes across all sheets
salt: this is a secret key
# optional: if true, then if any field is missing from the keys, then the
#         entire file will fail
is_strict: True
# a list of translations to apply
translations:
  # what sheet to apply the translations
  - sheet: SheetA
    # from which row (starting at 1) should the translations apply
    # if left out, then every row will be updated
    from_row: 2
    # The column names (A, B, C, etc) used to generate the keys
    key:
      - A
      - B
      - C
    # The column names to be wiped blank - these must be taken
    # from the columns used to generate keys
    # NOTE: the first column, above, will *ALWAYS* be replaced by the
    #     generated key
    hide:
      - A
      - B


  - sheet: This be a sheet
    from_row: 5
    key:
      - A
      - B
      - C
    hide:
      - A
      - B
      - C

  # if we ask for a sheet that's not here, we shouldn't break
  - sheet: Not a real sheet
    from_row: 5
    key:
      - A
      - B
      - C
    hide:
      - A
      - B
      - C